# Generated by Django 3.2.9 on 2021-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211124_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='department',
            field=models.ManyToManyField(to='accounts.Department'),
        ),
    ]
