# Generated by Django 3.2.9 on 2021-11-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_courses_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial',
            field=models.CharField(default='test .t', max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
