# Generated by Django 3.2.9 on 2021-11-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='lecturer_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='initial',
        ),
        migrations.AddField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='lecturer',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='accounts.lecturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='initial',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
