# Generated by Django 3.2.9 on 2021-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211127_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='initial',
        ),
    ]
