# Generated by Django 3.2.9 on 2021-11-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesWednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'courses_wednesday',
            },
        ),
        migrations.CreateModel(
            name='CoursesTuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'courses_tuesday',
            },
        ),
        migrations.CreateModel(
            name='CoursesThursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'courses_thursday',
            },
        ),
        migrations.CreateModel(
            name='CoursesMonday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'courses_monday',
            },
        ),
        migrations.CreateModel(
            name='CoursesFriday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.lecturer')),
            ],
            options={
                'db_table': 'courses_friday',
            },
        ),
    ]
