# Generated by Django 3.2.9 on 2021-11-25 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_venue_name'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('class_start_time', models.TimeField(blank=True, null=True)),
                ('class_end_time', models.TimeField(blank=True, null=True)),
                ('course_code', models.ForeignKey(blank=True, db_column='course_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.lecturer')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursesmonday',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='coursesmonday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursesmonday',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='coursesthursday',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='coursesthursday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursesthursday',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='coursestuesday',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='coursestuesday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursestuesday',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='courseswednesday',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='courseswednesday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='courseswednesday',
            name='lecturer',
        ),
        migrations.DeleteModel(
            name='CoursesFriday',
        ),
        migrations.DeleteModel(
            name='CoursesMonday',
        ),
        migrations.DeleteModel(
            name='CoursesThursday',
        ),
        migrations.DeleteModel(
            name='CoursesTuesday',
        ),
        migrations.DeleteModel(
            name='CoursesWednesday',
        ),
    ]
