# Generated by Django 3.2.9 on 2021-11-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_venue_name'),
        ('timetable', '0002_auto_20211125_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='department',
        ),
        migrations.AlterField(
            model_name='table',
            name='class_end_time',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='class_start_time',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='venue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.venue'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wenesday', 'Wenesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('level', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level')], max_length=3)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.table')),
            ],
        ),
    ]
