# Generated by Django 3.2.9 on 2021-12-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_lecturer_initial'),
        ('timetable', '0004_auto_20211127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(default='SE', on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.table'),
        ),
    ]
